image: ruby:2.4.0
services:
  - postgres:latest
before_script:
  - mkdir -p /cache/bundle
  - ls -lAh /cache/bundle
  - bundle check --path=/cache/bundle || bundle install --path=/cache/bundle --without=production,development,deploy,doc
  - git status --short && test "$(git status --short | grep Gemfile.lock)" = ""
variables:
  RAILS_ENV: test
  RACK_ENV: test
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: ""
  CODECLIMATE_REPO_TOKEN: "6a0ebd93163ba27e304598507d4708c3ef92453ba5005bf9b8dafb1fe6d6a80e"
lint:
  stage: test
  tags:
    - ruby
  artifacts:
    paths:
      - rubocop.html
  script:
    - bundle exec rubocop --rails --fail-level=warning --display-cop-names --format=progress --format=offenses --format=html --out="rubocop.html"
test:
  stage: test
  tags:
    - ruby
    - postgres
  artifacts:
    paths:
      - coverage/
  script:
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake assets:precompile
    - bundle exec rake test
    - bundle exec codeclimate-test-reporter
